### ISSUE TITLE
Can not use Seurat::DimPlot with css reduction

### ISSUE THREAD

**Issue by kaizen89** [quadbiolab/simspec#1]
Hi,
I have tried your tool on a seurat object but then  when I wanted to do:
```
DimPlot(object, reduction="css"
Error in `[.data.frame`(data, , c(dims, x, split.by, shape.by)) : 
  undefined columns selected
```
In addition I have looked at the reduction slot and I found that the columns names were repeated several times
```
colnames(Embeddings(object[["css"]]))[1:10]
"CSS_0" "CSS_1" "CSS_2" "CSS_3" "CSS_0" "CSS_1" "CSS_2" "CSS_3" "CSS_0" "CSS_1"
```
Do you know what is causing these two issues?

**Comment by zhisonghe** [comment]
Hi,
Thanks for asking. This problem is due to the duplicated colnames of the CSS matrix. Now it has been fixed.
However, unlike PCA, each column of the CSS matrix represents similarity to one cluster, therefore, different columns of the CSS matrix are of equal importance. In that case, using DimPlot to visualize individual columns of the CSS matrix may not show the information you want to check. If you have done RunUMAP after running CSS just as the README shows, please use UMAPPlot directly to visualize the CSS-based UMAP embedding.

**Comment by kaizen89** [comment]
What about the Clustering on the css reduction? Does it make sens?

**Comment by zhisonghe** [comment]
The README is just updated to include clustering.
The answer is yes. Similar to RunUMAP, you have to specify reduction to be "css", and dims to be all columns of the css representation, when running the FindNeighbors function

**Comment by kaizen89** [comment]
Thank you
