### ISSUE TITLE
no slot of name "data" for this object of class "Assay5"

### ISSUE THREAD

**Issue by leecon30** [quadbiolab/simspec#11]
Hi ive been running through your multiome tutorial with two biological replicates, however I encounter this issue no slot of name "data" for this object of class "Assay5" when i attempt to use cluster_sim_spectrum. I think it might be due to the use of Seurat V5 based on similar incompatibilities with other packages i see online. Do you think it would be possible to provide a fix for simspec? 

Thanks,
Lee

**Comment by HuandingJi** [comment]
Hi, I encountered this exact same problem when analyzing public datasets. I manage to make it work again by cloning a repo of this package from Github, made some modifications to the code, and then locally installed it into R. But I cannot promise this is the most correct approach. 

I saw in this [document](https://cran.r-project.org/web/packages/SeuratObject/SeuratObject.pdf) about the difference between **Assay-class** and **Assay5-class**. I think this package is built upon Assay-class, which contain slots like `counts`, `data`, `scale.data`, `assay.orig`, etc.; but the newer version of Seurat uses the Assay5-class, which contain slots like `layers`, `cells`, `features`, `default`, etc. And this is where the problem arises. 

I tried to find the corresponding script in where R packages are installed, however I didn't manage (maybe because I'm not familiar with its setup in general). So instead I cloned this package from this repo by Terminal command `git clone https://github.com/quadbio/simspec.git` to an arbitrary directory, and then under folder /simspec/R/, find the R file **css.r**, open it with RStudio.

Starting from line 381, change `data <- object[[object@active.assay]]@data[var_genes,]` to: 
```
  data <- object[[object@active.assay]]@layers$data
  row.names(data) <- row.names(object)
  colnames(data) <- colnames(object)
  data <- data[var_genes, ]
```
change `data <- object[[object@active.assay]]@scale.data[var_genes,]` to: 
```
    data <- object[[object@active.assay]]@layers$scale.data # CHANGE MADE TO ORIGINAL CODE
    row.names(data) <- row.names(object@reductions[["pca"]]@feature.loadings) # CHANGE MADE TO ORIGINAL CODE
    colnames(data) <- row.names(object@reductions[["pca"]]@cell.embeddings) # CHANGE MADE TO ORIGINAL CODE
    data <- data[var_genes, ] # CHANGE MADE TO ORIGINAL CODE
```
change `dr_input <- object[[object@active.assay]]@data[var_genes,]` to: 
```
      dr_input <- object[[object@active.assay]]@layers$data
      row.names(dr_input) <- row.names(object)
      colnames(dr_input) <- colnames(object)
      dr_input <- dr_input[var_genes, ]
```
and change `dr_input <- object[[object@active.assay]]@scale.data[var_genes,]` to: 
```
      dr_input <- object[[object@active.assay]]@layers$scale.data 
      row.names(dr_input) <- row.names(object@reductions[["pca"]]@feature.loadings)
      colnames(dr_input) <- row.names(object@reductions[["pca"]]@cell.embeddings)
      dr_input <- dr_input[var_genes, ]
```
Then save the changes, in a R terminal, change working directory to where this folder is located (`setwd(".../simspec/")`), install devtools package if not yet installed, then run `devtools::install()`. After the installation completes, run `library(simspec)`. In my case, then everything is back to working. 

Here is a screenshot from RStudio of all the changes I made [screenshot.pdf](https://github.com/quadbio/simspec/files/13688376/screenshot.pdf).

**Comment by leecon30** [comment]
Hi thanks very much this is brilliant - Ill try run it now. Sorry for the long response time i shelved the analysis for a hot min - that's hand that was resolved.

**Comment by leecon30** [comment]
im coming up with this error and I have the new modified simspec css.R file. 

> library(simspec)
> seurat <- cluster_sim_spectrum(seurat,
+                                labels = "orig.ident",
+                                cluster_resolution = 0.6,
+                                reduction.name = "css_rna",
+                                use_scale = T,
+                                reduction.key = "CSSRNA_")
Error in `rownames<-`(x, value) : 
  attempt to set 'rownames' on an object with no dimensions"

**Comment by zhisonghe** [comment]
Hi, thanks both for the comments. I'm now working on incorporating the package with Seurat v5. Once it is done I will post the information here.

**Comment by zhisonghe** [comment]
I just pushed the update of simspec. Now it should have supported the Assay5 object in Seurat v5. Let me know if you still encounter any issue.

**Comment by leecon30** [comment]
Thanks very much I'll give it a go. I'd like to incorporate this into my
work. So that will be great if it works.

Cheers,
Lee
