### ISSUE TITLE
Error in asMethod(object) :    Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

### ISSUE THREAD

**Issue by Songlei-L** [quadbiolab/simspec#4]
Hello developers,

I got the following prompt when running the code:
```
Finished clustering.
Obtained average profiles of clusters.
Start to calculate standardized similarities to clusters...
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
```

After looking into the source code of "cluster_sim_spectrum()", it seems that the problem is likely from this line:
`cor(as.matrix(data), profiles, method=corr_method)`
where as.matrix() is converting the sparse matrix into a regular matrix, causing the memory to overflow.

I'm working with a matrix with ~1 million cells and ~30k genes. And 200GB memory was allocated.

Am I identifying the problem correctly? And do you have any suggestions on adapting your methods to large datasets?

Thank you very much!

**Comment by zhisonghe** [comment]
Hi there,

Thanks a lot for contacting. You are right, this problem is due to the matrix being too big making the as.matrix function being failed.

By default, for CSS calculation Spearman correlation is calculated between the cell expression and cluster expression. Unfortunately, we don't know any good Spearman correlation implementation on sparse matrix, and that's why we sticked to the way of converting the expression matrix into the dense matrix and using the base cor function to calculate. For Pearson correlation, on the other hand, there are implementations on sparse matrix (e.g. qlcMatrix::corSparse) which can avoid converting into a dense matrix. We will incorporate it into our script.

**Comment by zhisonghe** [comment]
Dear User,

We have modified the script to support using qlcMatrix::corSparse to calculate Pearson correlation for sparse matrix. You can update the simspec package to use the function. Please make sure that qlcMatrix (>=0.9.4) is installed and specify the corr_method parameter to be pearson.

Another comment I have is that please also try to avoid using all genes for CSS calculation. It slows down and worsens the calculation by introducing noises from genes without strong variations between cells or cell types. Use the highly variable features only would be the recommended way.

Hope this would help.

**Comment by Songlei-L** [comment]
Thank you very much for fixing this quickly! I no longer get this error message.

Regarding your comment on avoiding using all genes for CSS calculation, if I start with a Seurat Object where variable features have been identified (i.e. 3000 features), but the count matrix slots (raw, normalized, scaled) still have all genes (i.e. 30k genes), would the program select for variable features automatically? or should I subset the count matrix first to avoid using all genes for CSS? Asking because I don't see an option in cluster_sim_spectrum() to indicate a specific gene/feature list.

Thank you!

**Comment by Songlei-L** [comment]
Ah I see these lines:

> var_genes Genes used for similarity calculation. If NULL, predefined variable features are used
```
if (is.null(var_genes))
    var_genes <- Seurat::VariableFeatures(object)
```
This answers my follow up question about features used for CSS calculation. Thank you again!
