### ISSUE TITLE
Any interest in supporting python?

### ISSUE THREAD

**Issue by hyjforesight** [quadbiolab/simspec#6]
Hello CSS,
Thanks for developing this amazing package. I think it solves the problem that other integration methods do too much correction when doing integration, leading to the removal of biological differences.
Due to the low speed of R, is there any interest in making this package support python?
Thanks!
Best
YJ

**Comment by zhisonghe** [comment]
Hi YJ,

Thanks for the suggestion, and sorry for the long delay of replying due to my personally issue. We will definitely take it as a motivation to do that. It is principally not too difficult as well. Once we have any progress we will let you know. However, I'm afraid that it will be limited to R in short term, due to the limited time I have at the moment to implement it.

All the best,
Zhisong

**Comment by zhisonghe** [comment]
The Python script is now implemented, and currently on the way of wrapping up. Will comment in the README once there is more updates

**Comment by hyjforesight** [comment]
@zhisonghe Thank you! Look forward to it!

**Comment by RijndertAriese** [comment]
Hi, 

I would also be interested to use the python implementation, but I cannot find this in the readme at this point. Did you implement it in the end?

Thanks!

**Comment by eva-artano** [comment]
Hello, 
Thank you very much for this integration tool that allows us to work efficiently with cell development data. However, I can’t find the script in Python. Is it still available?

Thanks
Best, 
EA
